server:
  port: 7001
  servlet:
    # controller root path
    context-path: /ad-search # controller 的前缀，sponsor-广告检索系统

spring:
  application:
    name: eureka-client-ad-search
  jpa:
    # orm 数据库增删查改
    show-sql: true # 打印语句
    hibernate:
      ddl-auto: none
    properties:
      hibernate.format_sql: true
    open-in-view: false
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/imooc_ad_data?autoReconnect=true
    username: root
    password: aliceh9501@outlook.com
    tomcat:
      max-active: 4
      min-idle: 2
      initial-size: 2

eureka:
  client:
    service-url:
      defaultZone: http://server1:8000/eureka/

feign:
  hystrix:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*" # 暴露全部监控信息
